apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-openbsw-vault
namePrefix: vaultwarden-

buildMetadata: [originAnnotations]

resources:
- manifests/postgres/
- manifests/mailcatcher/
- manifests/vaultwarden/

