apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:JHMfC9GB9r+F2VbOz1hwkln9WnU=,iv:wHTMlceQmD63LXwHlBIujRzIcAyIgKdVf4oSVW2GYKo=,tag:7IsSeo0juHJANME8tocS4A==,type:str]
    username: ENC[AES256_GCM,data:B477FQpVuSLYbjE=,iv:tXS3qG03irwj3bQawTre6TOgfQuNj2/6F8ksymEzJnI=,tag:DXHDHIsWiZq6Kj7JfBX5dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbFlJU29lMC9qQ0gvRE1k
            ejB2dU9jTEFyU1FtMEVLRmZUR1pQZmtEYUZRCm5yb2RsVFZNMlpkSmhVYWdjY3Np
            VEVuMElHNkI1NVJ4NXZDem11YmN5QU0KLS0tIHM2RC9iRktuajF2ME1vT0ducmtB
            ajBtZGZURk9PREJ6YXIyQm5tVjdJODQKmCIC8McelEOIwgWPUdKfxME4pwQmpWJD
            byvhEU+64v/81i4shVg8bWZ5IGDzi06nmvoNF1FnnYz9rua3KwwZLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T17:56:17Z"
    mac: ENC[AES256_GCM,data:OfJZZ6JdLs446M47TbON5n0z0DF2GkfXl0IdEc7kZH2OluubevgS0rWwFLqDJzm7TX7+/EgSwLjMfW5EfbmIxAUWSmZIpmkdtpeh+2JzhDPJUQSq6QK46bLj+g1fi1VDoDc+6JCon2Zb2ZjVihvmyHh6h7D0B3/AsTCjq34/QQY=,iv:8vzAJfyG+PkffIAfSV8xggv043Gk6Pm4iOJn7CbFNG0=,tag:4fUtq9M+WnfhmEGXC72dpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
