apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:BW4+q8kVUy3sWyOtCqWVgkB7Gy8=,iv:eDHHiriLsmMjXrV2jPpxWEPcBIUfutPgS6YykXBK5+s=,tag:EP/czSM5KSKQs4yg+GMh1g==,type:str]
    username: ENC[AES256_GCM,data:3CH9onC9ojhuadU=,iv:BEKQAfdH56YPKAfpOvZM+AK5fsb9Ode55R6ACoHPU5s=,tag:CUw/kVpebIu8KRibI0oV4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hy33xl9l28mhv7ne2j6mju3wdswt9wy9vmmw0vv64syxw7hmmqas7sp73d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVh1OHI2TUhXd2lranVG
            VVNCZ0RDbWIxR0ltUjdmZ1VQR1pycFFiUDFFCnhLTFRHdHBsNnM3NXp1TGNmN00w
            eU9ZUURJMnZiYVdCNTRMM1djZlhEejgKLS0tIC95YWZLTDJaNTZ0SGJUVGp5SUda
            N3Z2NGNaOVZLZnNHcjdhVXlqSldZYzAKwrP73HJHQux3kRptK9CXjvAa0dUEPFCB
            2s/p0QDzo6W2n1S//O/a9z3gdnLJm4n+mJVIrSFq2ojJOmVys03H7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T18:47:40Z"
    mac: ENC[AES256_GCM,data:LS/dArUEhb4RRTY03pwO3kirgwILld+aLPDagkbs89agBvE0vrwdr93xgYIx0Sh7KLSbIZffIGOvZEDXR6o7yj4tqUhVVKqPhc0UDUGRUVhuhCknBJe0px4cVANTnylTko8zHbon73CrUVKpXQGgpFgmJ0QV9Ax67ZGzloYM8as=,iv:/acEaLByAjYJ8C9gJZhz4VfpUP7RBZEZM+tDxjpzYgo=,tag:RRnNYmc9zU7ks5SdQb6CGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
