apiVersion: v1
kind: Secret
metadata:
    name: sec-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:uQw1PpadIrlZq/00qRaozMAuNm4=,iv:6y3CQFDrH87AzOEqZaXE4cNmhucXaxJ9UinGTLVZKGA=,tag:mcY2ufsXMXzPx8pzcOfQuw==,type:str]
    username: ENC[AES256_GCM,data:Pv/S8s9iFQ8=,iv:3eCP9HEq1Mab6OW8d9iOiV1u1cAoCIZ/JLaOzQ8u0WY=,tag:x2BUPaeiv1BsrnaOo6HD0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hy33xl9l28mhv7ne2j6mju3wdswt9wy9vmmw0vv64syxw7hmmqas7sp73d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTUIzR0FmTzVTY0pKMXdN
            WTRnZHdScEpFUExZL1h6YkRWbDh0Ykk3cUdvCktQWnRDTzFid29mUWhCUW8zd3kr
            SFpLVHJqeHZoNFp4Z2hRZ2tDd0o3YTAKLS0tIEFMclpxRGZoSmpqaUxSRi9BUnZK
            NDdWQUU3K3JvS0VoN0FlKzlITGUzQkEKaYsYcPCQrYtPod05ZK5mH0NB+RKfkq1d
            hpRgD7kS1E5gwWEtCkmHvkqXp7mJOoMqtkaGRAVwUiRgBrFf4pE9+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T18:47:35Z"
    mac: ENC[AES256_GCM,data:Fx4kHRcoJqnxzoy0sss04vK319EKVPI88nYs0D3FIoerv/lxk9AyeQRKGpK/aKOlOBi/ISoPhJHFz3IfA6x4dYT9TTsDD2QzL/QZEcxw8nw8Cp2uFR/xVoL4EESZDkMX6RO5sLil+MJM81ebpseTk/nKLzWSzqMnSvaaixgRNXU=,iv:kIAW4XEBPEqWVqGSwYQXloWfEVcvnujbazMrfDN//2A=,tag:xOeK517QnFm79cHWHWajVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
