apiVersion: v1
kind: Secret
metadata:
    name: sec-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Rrjx5xKiEA4/XmcXYXL63X3rHDo=,iv:LcGwnoarnWvSDNb3wUf0kZt+LcD7Ya3j4acANfP8pl0=,tag:G0Ok6NxYgiBFQ1lC2gg1AA==,type:str]
    username: ENC[AES256_GCM,data:EqtBgdWTDck=,iv:W0tgrQJd6VA2T+8DZHTb9BLX20FCkoQTsWOH55ZmxOo=,tag:p7yaJRkyWrhQ2B5N7cXlgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QWVMZkoyTzlVZjRiMm9i
            UC9SbnNOYTZkYlpScld3aGxjcWs1TC9TTDBVCmU4eFhRaHdVUFhic1orWVpva0JQ
            UDNoeXpsR2ZSQkM3clVsT2ptYzY5bUEKLS0tIFozM1IxeDBzR2YxUXlOYlU3NXlx
            UG5QNFVBZE9IRjhyZ005T2wyTkk1UTgKoYMFcEOLRhtP2t42LszzSmVPht3VqF6/
            YZI8w8krxy0aiUn7BnWXQhwC9CX5G9fFbTB1j8W73/bgtDW8SBJF6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T17:56:13Z"
    mac: ENC[AES256_GCM,data:zFB6fVbqOG2XdisLWS2ALWjKFzJ14OhTvM6whg0HQ8xejBpv8jUz3hOFlVVq9V/10Gp1UblZVrgUhpAYSMyxtVBJ8Pe+JKmsjOl2f0i+X79yVSgPSZDRpUISUf8TJ9gKbpa61NzGpLTTIdih9sKfyYEhpLPg1gaTRVeImnBwwCE=,iv:evn7r0smlxnx3BKKxh9FTrqeXcm7jlXh29KO9Ngegn8=,tag:oUEg0XQnkaQidz/I60O9UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
