apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:9wf6J+frOiisRJ7rLuzwumd+ottKb/mcYsJLQExphANi7wwnGwROZQbPv1FDvOF7osgnqtnb8vTFBJI3RsQl+ky2sCRQTKMij5TOSil7IWscsjE7EhVFPIWA91Vd5Pgl7pfYw1JdpXvECGw=,iv:oZJBKVtlBh7oPxqpH3rx0TxhIA03tQfTAORPY1Yqbls=,tag:N3sNgZp3hvFZhNu+G8w8NQ==,type:str]
    ORG_CREATION_USERS: ENC[AES256_GCM,data:ZEcdrMzDnPfbtlSk6jtJo2i6VF+rVuLhCAPtOog=,iv:6UQ+PyYoH3jh7WqKmajilgIFFPsDcTLr+0D5EQrGJLs=,tag:9yc9QRBz37sfpRYrXSev2A==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:Nx0ZUcAkIFpl7ZEdXRTKhWGXdvpiM2jVHpI7YhTLGV84N0t2mmA1r1Cj7uVwchXkkn1xy0BS/YJdwfmGXoC2KoX5gFh+amLVYaPv+YsoR174YKAmMIvzzPMWPH+uHP6XvOa/gZINfekkIfm+qulV2vqk1uvtqQ==,iv:DUazbdEgEWy96XvrbSBqFGh0AZU+Q+AMrtWUvSHzpPw=,tag:YRMm1GdLpntA5W6YBMAPwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNmQ3d3ZRWHp4REFJMXZJ
            dEJHR1JzMkE1cTJETWJHZTNWcUkzak5CSGdJCjhMaExzd2pyVFdKRlFXY3Z1MEVP
            aHZPZTl5a1RZNEhaaGRYVk9zYy9qL2cKLS0tIFVMOWlxVnJHZ0F2NHZBc1pwUVdC
            ZzRCcDNISnhnVVFISVFzaXdwR3Uvb2cK/fmW+0jzxmSj/X7vUDnPO54bzXNxQm41
            vC4XbvbBoiarMmCWl+LK33c7sife5krplkP7P5lczaaCv6qDxcPftA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T17:56:27Z"
    mac: ENC[AES256_GCM,data:fDRiEMkHB8JfRqkj9Bn5nlJagYfXtJWz0gr/Gh+xQkGFcUx6iR5otFyyoTJ/tCPbg003gvEXqeFCIgMydW4JYC0pAIbS8vhvUInAS0y5iT3sPS1BKQU15iH8Rumti7nihcsIqMuQG3huhHFLuLxt0gpX4wnOjyC7k9v3ZchwLlI=,iv:keO5YHyM6BZjJb8E4gZfVeUHSz+qVNL9+xG2BPBNpJM=,tag:aDtrcGAzXAFyI5JFeUICQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
