apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:coZNRj0zwEGiIZ10MR0fPGSaTyn9e0swvKM2afWQdcFQqFCu/WuSB4hHp4UNL+VIKSoO5zxxFInpCatONZOeNeVIXY+3BzpGwqLWvqGqmn5YIrZE8QX0aK+iVThMluFxwpc4LWRpDo8sYlE=,iv:sU1u3xRgVlvELHUBcH6iyoDiA8DHpHdk7z7Kxu0MuVs=,tag:DyOZSgq7B4i7P8F4QJsu4A==,type:str]
    ORG_CREATION_USERS: ENC[AES256_GCM,data:ffrgUmL2mN0uQPhtQYzyUgV+y1eJJX/uv+QeIMY=,iv:ZZ5IAwGLrlWpnZIOy3ssSJokol09FHY6cxH4kz3+Qu8=,tag:0wadRqPelVMKPZd8TzPe1w==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:lCtesH2AYuzHiwzyRyOPv4JbENeBW8sTEC4n5tfFWke7VsokkAEZbpBlaxJv5kZ9mJMRWtHg2W52y9uY+rBgm/ii7Cu612n51L2zbQ9b7qhbX+e4Pjm25rZT4uU9wMqxP8/hnuo1iZ6qR+Z94Ru4dKQApv3Tpw==,iv:JCQNv4cb4jcUGqbd/alPpHpsDBplX6gfpCcRoAOHp7g=,tag:kcPssR+m5NfWifKQyvhSZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hy33xl9l28mhv7ne2j6mju3wdswt9wy9vmmw0vv64syxw7hmmqas7sp73d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMTBhSDQrYk1GODhpTXh6
            eno0N3NSYXBodno3QzVxa05XdUkzTDNIeVJZCllpWGg4RGx5bkVkdExNL0oxWVgv
            dE4wRjVrRGUrSU5FVENYL1E0REFIMmcKLS0tIGltZEQ2MHhBUUdsYjJPMXRwRjVD
            cnlhYWQzSlZ4MGRsb3dUdWdzQTFDQzgKe66ABhIl3tCxTSMkDWrD2tJtD8zLP9K4
            rqykFz2weMHdF3JULJj5kFfEW5npl7TicYAcIDOd8+3Q3uGaNBo6jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T18:47:51Z"
    mac: ENC[AES256_GCM,data:JyZfh0WE4ZXho/XFlFU70e0gKwfo4PJxwIscePA/+nAFAMjHquIE2BbmJE60ctW3am2zDa+39IVrO18B0hJ1iZCrPgCaSNKaPo7z4vB50FSgPH96JMxUhkYb2TngsH4MT7WxQzLw2BbXY+0wKGyo/CUANbbSihg7NNEDJkKtzng=,iv:e0LRVHk27jaG001J9ySGl2SSyBiBos5PnjZIfy6C5PI=,tag:qam4pchm4tCsRNrIaH20+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
